### ISSUE TITLE
Texture is shown incorrectly in examples/viewer

### ISSUE THREAD

**Issue by mickey9294** [syoyo/tinyobjloader#134]
I built tinyobjloader and its **viewer** example. When I loaded a ojb model with mtl texture in the viewer, I found that the texture color is not right.
For example, the obj can be correctly displayed in MeshLab as the following picture:
[bag_in_meshlab.png](https://drive.google.com/open?id=0Bx6oPOrZ8yi0eU94NGJhV0RTRGc)
But when I load it in examples/viewer, it looks like the following picture:
[bag_in_objviewer.png](https://drive.google.com/open?id=0Bx6oPOrZ8yi0UGxmeHhHckdYSGs)

The obj file and its texture I used as well as the project files are in the attachments:
[bag.zip](https://github.com/syoyo/tinyobjloader/files/1206988/bag.zip)
[viewer.zip](https://github.com/syoyo/tinyobjloader/files/1206981/viewer.zip)
The project is built on Visual Studio 2015

Could you please tell me how to fix it?

**Comment by syoyo** [comment]
At least loaded texture coordinate looks correct.

During investigation I found tiny bug and fixed it in recent`master`

Currently OpenGL viewer example does not support per-face material, thus you are better first grouping faces(triangles) based on material IDs.

PR are always appreciated!

**Comment by mickey9294** [comment]
I don't quite understand why the color of the texture is incorrect, because I'm a beginner of OpenGL. Could you please explain more specifically and tell me how to do?

**Comment by syoyo** [comment]
Please learn OpenGL firstly.

**Comment by chrisliebert** [comment]
The viewer example combines the calculated normal with the Wavefront diffuse color (see viewer.cc line 396). Before texture support was added, the models were colored based on the calculated normal in a color array and this was a helpful way to show the geometry without attempting to implement all of the material properties in OpenGL. I submitted the pull request to support textures, and did not want to make the viewer no longer functional on non-textured models that didn't have a diffuse texture defined. Currently the example demonstrates how to use the texture coordinates, but does not attempt to implement all the features of Wavefront since that would involve many corner cases and potential optimizations that would complicate the code significantly and are unrelated to tinyobjloader itself.

**Comment by mickey9294** [comment]
@chrisliebert I got it. Thank you

**Comment by TheJavaProfessor** [comment]
Here is the fix for fixing the textures right:
To avoid 'gaps'...:
change line in viewer.cc in function LoadObjAndConvert(...):

      if (shapes[s].mesh.material_ids.size() > 0 && s <= shapes[s].mesh.material_ids.size() ) {

to:

      if (shapes[s].mesh.material_ids.size() > 0 ) {

Important (main fix)
Also, if your .obj file contains more textures, like one for every face, save it (i.e. blender) with SEPERATED faces. Not combined as one face, then it only uses the first texture as programmed.
So then every face will has its own texture.

Maybe adapting line:
 >> 
      o.material_id = shapes[s].mesh.material_ids[0];  // use the material right 
<<

with diff. value will get right material_ids[x] when one face... (Dunno, have to check it now...) (finding x)

https://drive.google.com/open?id=1fQmw_dphx_zJJbTd5cB68CrEmwHJdWJp

https://github.com/TheJavaProfessor/MINECRAFT-WORLD-CREATOR/blob/master/Naamloos.png

**Comment by TheJavaProfessor** [comment]
https://www.youtube.com/watch?v=uqV3do_1f8s

Works perfect.
The cube is opengl sfml.
The face is code from https://www3.cs.stonybrook.edu/~gu/tutorial/MeshViewer.html
And the piece of city is from earth reversed engineering shown with viewer.exe (this thing).

**Comment by syoyo** [comment]
Awesome! > @TheJavaProfessor 

I'll close this issue
