### ISSUE TITLE
get color from mtl file

### ISSUE THREAD

**Issue by anirudt** [syoyo/tinyobjloader#143]
How to obtain colors of vertices from the MTL file associated with the OBJ file?

**Comment by syoyo** [comment]
.obj spec does not support vertex color.

PR for vertex color through extension is always welcome!

https://blender.stackexchange.com/questions/31997/how-can-i-get-vertex-painted-obj-files-to-import-into-blender

**Comment by anirudt** [comment]
I see, thank you.

Does OBJLoader offer support for finding color through the texture maps specified in the MTL file?

**Comment by syoyo** [comment]
> Does OBJLoader offer support for finding color through the texture maps specified in the MTL file?

This is not a job of obj loader.

You can write your own tool/application to do that. Writing example code and sending a PR are always welcome!

**Comment by syoyo** [comment]
You are better to study 3D graphics programming firstly, e.g. with

http://graphicscodex.com/

**Comment by bathal1** [comment]
Hello! 
It seems that tinyobjloader now supports vertex color loading, however when trying to upload the Cornell Box (from your reppo, colors show up on blender) in my program, all vertex colors returned by tinyobj are set at (1,1,1). My code for importing the file is basically a copy-paste of your example file, so I have trouble understanding why I have these colors. Is this the expected behavior?

**Comment by syoyo** [comment]
Please attach minimal & reproducable .obj/.mtl
