### ISSUE TITLE
issue loading mtl file with spaces in file path

### ISSUE THREAD

**Issue by ejosiah** [syoyo/tinyobjloader#49]
Hi syoyo

while reading the obj file if it contains a mtllib directive with a file name like "Female Cyborg.mtl" the mtllib file name will incorrectly be parsed as Female (only extracts the first word before the space) this cause the MaterialFileReader to create default materials

**Comment by chrisliebert** [comment]
The space in the filename is invalid Wavefront specifications because official specs state multiple .mtl files can be loaded with one "mtllib" declaration. I have created the following c++ tool to fix/rename obj and corresponding mtl file:

<pre>/* A tool for converting spaces to underscores for 
wavefront .obj files and their associated .mtl files */

#include &lt;cstdlib&gt;
#include &lt;fstream&gt;
#include &lt;iostream&gt;
#include &lt;string&gt;
#include &lt;sstream&gt;

using std::cerr;
using std::cout;
using std::endl;

using std::fstream;
using std::ifstream;
using std::ofstream;
using std::string;

void replaceAll(std::string&amp; initial_str_content, const std::string&amp; search_str,
                const std::string&amp; replace_str)
{
    size_t pos = 0;
    while((pos = initial_str_content.find(search_str, pos)) != std::string::npos)
    {
        initial_str_content.replace(pos, search_str.length(), replace_str);
        pos += replace_str.length();
    }
}

// Return the obj string with spaces converted to underscores
const char* getProcessedObjFileContents(const char* filename)
{
    string new_contents(&quot;&quot;);
    string line;
    ifstream obj_file(filename);
    if(!obj_file.is_open())
    {
        cerr &lt;&lt; &quot;Unable to open &quot; &lt;&lt; filename &lt;&lt; endl;
        exit(1);
    }
    while(getline(obj_file, line))
    {
        if(line.substr(0, 7).compare(&quot;mtllib &quot;) == 0)
        {
            string new_filename = line.substr(7);
            // Rename the .mtl file (replace spaces with underscores)
            replaceAll(new_filename, &quot; &quot;, &quot;_&quot;);
            if(rename(line.substr(7).c_str(), new_filename.c_str()) != 0)
            {
                cerr &lt;&lt; &quot;Unable to rename &quot; &lt;&lt; filename &lt;&lt; &quot; to &quot; &lt;&lt; new_filename &lt;&lt; endl;
                exit(2);
            }
            line = &quot;mtllib &quot; + new_filename;
        }
        new_contents += line + &quot;\n&quot;;
    }
    obj_file.close();
    return new_contents.c_str();
}

int main(int argc, char** argv)
{
    if(argc &lt; 3)
    {
        cerr &lt;&lt; &quot;Usage: &quot; &lt;&lt; argv[0] &lt;&lt; &quot; obj file with spaces .obj&quot; &lt;&lt; endl;
        return -1;
    }
    string filename(argv[1]);
    for(int i=2; i&lt;argc; i++)
    {
        filename += &quot; &quot; + string(argv[i]);
    }

    string new_filename(filename);
    replaceAll(new_filename, &quot; &quot;, &quot;_&quot;);
    ofstream obj_file(new_filename.c_str(), std::ios::trunc); // overwrite file
    if(!obj_file.is_open())
    {
        cerr &lt;&lt; &quot;Unable to open &quot; &lt;&lt; filename &lt;&lt; endl;
        return -2;
    }
    obj_file &lt;&lt; getProcessedObjFileContents(filename.c_str());
    obj_file.close();
    if(remove(filename.c_str()) != 0)
    {
        cerr &lt;&lt; &quot;Unable to remove &quot; &lt;&lt; filename &lt;&lt; endl;
        return -3;
    }
    cout &lt;&lt; &quot;converted &quot; &lt;&lt; filename &lt;&lt; &quot; to &quot; &lt;&lt; new_filename &lt;&lt; endl;
    return 0;
}
</pre>

**Comment by syoyo** [comment]
As in #46, strictly said, white space is not allowed in mtl filename. 

@chrisliebert This is super cool! Can I include this tool into `tinyobjloader` as an example?

**Comment by chrisliebert** [comment]
Feel free to include/modify this tool with/as an example. I only tested it on Windows, it might require tweaking on Unix to support escaped filenames (containing spaces): a script could be used to extract the escaped filenames and send them as separate arguments to the executable.

**Comment by ejosiah** [comment]
Thanks @chrisliebert  and @syoyo as this is not a bug I'll close this issue.
