### ISSUE TITLE
Wrong number of shapes reported

### ISSUE THREAD

**Issue by redagito** [syoyo/tinyobjloader#68]
The tinyobj loader reports 2 shapes for an obj file containing only 1 shape (1 object group, "o").
This used to work in earlier versions and only became an issue after updating to the latest version (Master).
I am loading only the obj file without an mtl file.

Edit: Seems I cannot seem to upload the affected mesh file, I will provide a direct link to the file in my repository
https://github.com/redagito/CG2015/blob/master/data/mesh/enemy.obj

I suspect the line 812: 
> usemtl Material.003

to be the cause of the problem

Edit 2: Removing the line fixed the issue, it should still be considered a bug though

**Comment by syoyo** [comment]
Thanks! for some reason, tinyobjloader changed to create an shape after `usemtl` line.
But expected behaviour may be 2 materials(per-face material) in one shape('o' tag).
(At least importing your .obj in Blender behaves like this).

First, we need to check wavefront .obj specification so that what is the correct interpretation of `usemtl` defined in the middle of .obj.

**Comment by syoyo** [comment]
Now `usemtl` does not create new shape.

BTW I'd like to add your .obj as a regression test set for tinyobjloader. Are you OK to add your enemy.obj to tinyobjloader repo?

**Comment by redagito** [comment]
Thank you for resolving this issue so quickly. Feel free to use the obj file for regression testing.
